# Generated by Django 4.2.7 on 2026-02-20 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('innovator', 'Innovator'), ('ngo', 'NGO'), ('beneficiary', 'Beneficiary'), ('admin', 'Admin')], default='innovator', max_length=20)),
                ('organization', models.CharField(blank=True, default='', max_length=200)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('te', 'Telugu'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi'), ('or', 'Odia'), ('as', 'Assamese'), ('ur', 'Urdu')], default='en', max_length=5)),
                ('notif_email', models.BooleanField(default=True)),
                ('notif_pilot_updates', models.BooleanField(default=True)),
                ('notif_team_activity', models.BooleanField(default=True)),
                ('notif_weekly_digest', models.BooleanField(default=False)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('team', 'Team Only'), ('private', 'Private')], default='team', max_length=20)),
                ('activity_status', models.BooleanField(default=True)),
                ('usage_analytics', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
                ('activity_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('target_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_members', models.IntegerField(default=0)),
                ('target_beneficiaries', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('ai_plan', models.TextField(blank=True, default='')),
                ('ai_ngo_recommendations', models.JSONField(blank=True, default=list)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_ngo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pilots', to='core.user')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pilots', to='core.user')),
            ],
            options={
                'db_table': 'pilots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='fa-bell', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.user')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pilot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.user')),
            ],
            options={
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('materials', 'Materials'), ('food', 'Food & Refreshments'), ('venue', 'Venue'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.pilot')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_role', models.CharField(choices=[('lead', 'Team Lead'), ('member', 'Member'), ('volunteer', 'Volunteer')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.pilot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='core.user')),
            ],
            options={
                'db_table': 'team_members',
                'unique_together': {('user', 'pilot')},
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_attended', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=10)),
                ('badges_earned', models.JSONField(blank=True, default=list)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.pilot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.user')),
            ],
            options={
                'db_table': 'beneficiary_enrollments',
                'unique_together': {('user', 'pilot')},
            },
        ),
    ]
