# Generated by Django 4.2.7 on 2026-02-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orgmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='tasks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
