# Generated by Django 4.2.7 on 2026-02-21 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pilot_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_admin', 'Pending Admin Approval'), ('pending_ngo', 'Pending NGO Acceptance'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='PilotAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_admin', 'Pending Admin Approval'), ('admin_approved', 'Admin Approved — Awaiting NGO'), ('ngo_accepted', 'NGO Accepted'), ('ngo_rejected', 'NGO Rejected'), ('admin_rejected', 'Admin Rejected')], default='pending_admin', max_length=30)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('admin_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ngo_notes', models.TextField(blank=True, default='')),
                ('ngo_responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_reviews', to='core.user')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.pilot')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='core.user')),
                ('requested_ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_requests', to='core.user')),
            ],
            options={
                'db_table': 'pilot_assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
