# Generated by Django 4.2.7 on 2026-02-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pilot_status_pilotassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(default='Certificate of Completion', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.user')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='core.user')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.pilot')),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
                'unique_together': {('beneficiary', 'pilot')},
            },
        ),
    ]
