# Generated by Django 4.2.7 on 2026-02-27 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_two_fa_enabled_user_two_fa_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_ngo', 'Pending NGO Acceptance'), ('pending_admin', 'Pending Admin Approval'), ('pending_payment', 'Pending Payment'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='pilotassignment',
            name='status',
            field=models.CharField(choices=[('pending_ngo', 'Pending NGO Acceptance'), ('ngo_accepted', 'NGO Accepted — Awaiting Admin'), ('ngo_rejected', 'NGO Rejected'), ('admin_approved', 'Admin Approved — Awaiting Payment'), ('admin_rejected', 'Admin Rejected'), ('payment_pending', 'Payment Pending'), ('payment_done', 'Payment Completed — Active')], default='pending_ngo', max_length=30),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=256)),
                ('status', models.CharField(choices=[('created', 'Order Created'), ('paid', 'Payment Successful'), ('failed', 'Payment Failed')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.pilotassignment')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.pilot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.user')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
