# Generated by Django 4.2.28 on 2026-02-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_payment_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='team_role',
            field=models.CharField(choices=[('lead', 'Team Lead'), ('data_analyst', 'Data Analyst'), ('budget_manager', 'Budget Manager'), ('community_organizer', 'Community Organizer'), ('field_coordinator', 'Field Coordinator'), ('member', 'Member'), ('volunteer', 'Volunteer')], default='member', max_length=20),
        ),
    ]
