# Generated by Django 4.2.28 on 2026-02-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_teammember_team_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_ngo', 'Pending NGO Acceptance'), ('pending_admin', 'Pending Admin Approval'), ('pending_payment', 'Pending Payment'), ('active', 'Active'), ('pending_completion', 'Pending Completion Approval'), ('completed', 'Completed'), ('paused', 'Paused')], default='draft', max_length=20),
        ),
    ]
